# TOC
1. Preparation & Data import
2. Exercise
3. View descriptive stats
4. Removing unnecessary column
5. Checking for mixed type columns
6. Finding missing values and analyzing them
7. Checking for duplicates
8. Exporting dataframes

### Prep

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Importing data
path = r'C:\Users\Ryzen RGB Madness!!!\Instacart Basket Analysis'

In [3]:
path

'C:\\Users\\Ryzen RGB Madness!!!\\Instacart Basket Analysis'

In [4]:
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Original', 'products.csv'), index_col = False)

In [5]:
df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Cleaned', 'old', 'orders_wrangled.csv'), index_col = False)

### Exercise

In [6]:
# Create a dataframe
df_test =  pd.DataFrame()

In [7]:
# Create a mixed type column
df_test['mix'] = ['a', 'b', 1, True]

In [8]:
df_test.head()

mix
0     a
1     b
2     1
3  True

In [9]:
# Finding missing values
df_prods.isnull().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [10]:
# Isolating null values
df_nan = df_prods[df_prods['product_name'].isnull() == True]

In [11]:
df_nan

product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14    12.2
68             69          NaN        26              7    11.8
115           116          NaN        93              3    10.8
261           262          NaN       110             13    12.1
525           525          NaN       109             11     1.2
1511         1511          NaN        84             16    14.3
1780         1780          NaN       126             11    12.3
2240         2240          NaN        52              1    14.2
2586         2586          NaN       104             13    12.4
3159         3159          NaN       126             11    13.1
3230         3230          NaN       120             16    14.4
3736         3736          NaN        41              8    14.8
4283         4283          NaN        77              7    14.4
4790         4790          NaN        91             16    14.5
38187       38183          NaN        39             12    20.9
40444       40440          NaN       120             16    14.8

In [12]:
# Creating df_prods with no null values
df_prods_clean = df_prods[df_prods['product_name'].isnull() == False]

In [13]:
df_prods.shape

(49693, 5)

In [14]:
df_prods_clean.shape

(49677, 5)

In [15]:
# Searching for duplicates
df_dups = df_prods_clean[df_prods_clean.duplicated()]

In [16]:
df_dups

product_id                                       product_name  \
462           462                  Fiber 4g Gummy Dietary Supplement   
18459       18458                                         Ranger IPA   
26810       26808               Black House Coffee Roasty Stout Beer   
35309       35306  Gluten Free Organic Peanut Butter & Chocolate ...   
35495       35491                            Adore Forever Body Wash   

       aisle_id  department_id  prices  
462          70             11     4.8  
18459        27              5     9.2  
26810        27              5    13.4  
35309       121             14     6.8  
35495       127             11     9.9

In [17]:
df_prods_clean_no_dupes = df_prods_clean.drop_duplicates()

In [18]:
df_prods_clean_no_dupes.shape

(49672, 5)

In [19]:
df_prods_clean_no_dupes.to_csv(os.path.join(path, '02 Data', 'Cleaned', 'products_checked.csv'))

### Task

#### Step 2

In [20]:
# Viewing descriptive statistics for df_ords

In [21]:
df_ords.describe()

Unnamed: 0      order_id       user_id  order_number  \
count  3.421083e+06  3.421083e+06  3.421083e+06  3.421083e+06   
mean   1.710541e+06  1.710542e+06  1.029782e+05  1.715486e+01   
std    9.875817e+05  9.875817e+05  5.953372e+04  1.773316e+01   
min    0.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
25%    8.552705e+05  8.552715e+05  5.139400e+04  5.000000e+00   
50%    1.710541e+06  1.710542e+06  1.026890e+05  1.100000e+01   
75%    2.565812e+06  2.565812e+06  1.543850e+05  2.300000e+01   
max    3.421082e+06  3.421083e+06  2.062090e+05  1.000000e+02   

       order_day_of_week  order_hour_of_day  days_since_prior_order  
count       3.421083e+06       3.421083e+06            3.421083e+06  
mean        2.776219e+00       1.345202e+01            1.044488e+01  
std         2.046829e+00       4.226088e+00            9.308727e+00  
min         0.000000e+00       0.000000e+00            0.000000e+00  
25%         1.000000e+00       1.000000e+01            4.000000e+00  
50%         3.000000e+00       1.300000e+01            7.000000e+00  
75%         5.000000e+00       1.600000e+01            1.500000e+01  
max         6.000000e+00       2.300000e+01            3.000000e+01

In [22]:
# Re-viewing df_ords due to new column appearing
df_ords

Unnamed: 0  order_id  user_id  order_number  order_day_of_week  \
0                 0   2539329        1             1                  2   
1                 1   2398795        1             2                  3   
2                 2    473747        1             3                  3   
3                 3   2254736        1             4                  4   
4                 4    431534        1             5                  4   
...             ...       ...      ...           ...                ...   
3421078     3421078   2266710   206209            10                  5   
3421079     3421079   1854736   206209            11                  4   
3421080     3421080    626363   206209            12                  1   
3421081     3421081   2977660   206209            13                  1   
3421082     3421082    272231   206209            14                  6   

         order_hour_of_day  days_since_prior_order  
0                        8                     0.0  
1                        7                    15.0  
2                       12                    21.0  
3                        7                    29.0  
4                       15                    28.0  
...                    ...                     ...  
3421078                 18                    29.0  
3421079                 10                    30.0  
3421080                 12                    18.0  
3421081                 12                     7.0  
3421082                 14                    30.0  

[3421083 rows x 7 columns]

In [23]:
# Dropping generated repeated column Unnamed: 0 and re-importing
vars_list = ['order_id', 'user_id', 'order_number', 'order_day_of_week', 'order_hour_of_day', 'days_since_prior_order']

In [24]:
df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Cleaned', 'old', 'orders_wrangled.csv'), usecols = vars_list)

In [25]:
df_ords

order_id  user_id  order_number  order_day_of_week  \
0         2539329        1             1                  2   
1         2398795        1             2                  3   
2          473747        1             3                  3   
3         2254736        1             4                  4   
4          431534        1             5                  4   
...           ...      ...           ...                ...   
3421078   2266710   206209            10                  5   
3421079   1854736   206209            11                  4   
3421080    626363   206209            12                  1   
3421081   2977660   206209            13                  1   
3421082    272231   206209            14                  6   

         order_hour_of_day  days_since_prior_order  
0                        8                     0.0  
1                        7                    15.0  
2                       12                    21.0  
3                        7                    29.0  
4                       15                    28.0  
...                    ...                     ...  
3421078                 18                    29.0  
3421079                 10                    30.0  
3421080                 12                    18.0  
3421081                 12                     7.0  
3421082                 14                    30.0  

[3421083 rows x 6 columns]

In [26]:
# Setting column types to exclude from descriptive statistics
df_ords['order_id'] = df_ords['order_id'].astype('str')

In [27]:
df_ords['user_id'] = df_ords['user_id'].astype('str')

In [28]:
df_ords.describe()

order_number  order_day_of_week  order_hour_of_day  \
count  3.421083e+06       3.421083e+06       3.421083e+06   
mean   1.715486e+01       2.776219e+00       1.345202e+01   
std    1.773316e+01       2.046829e+00       4.226088e+00   
min    1.000000e+00       0.000000e+00       0.000000e+00   
25%    5.000000e+00       1.000000e+00       1.000000e+01   
50%    1.100000e+01       3.000000e+00       1.300000e+01   
75%    2.300000e+01       5.000000e+00       1.600000e+01   
max    1.000000e+02       6.000000e+00       2.300000e+01   

       days_since_prior_order  
count            3.421083e+06  
mean             1.044488e+01  
std              9.308727e+00  
min              0.000000e+00  
25%              4.000000e+00  
50%              7.000000e+00  
75%              1.500000e+01  
max              3.000000e+01

In [29]:
# Checking that zero is an applicable number for order_hour_of_day (ie, in place of midnight)
for col in df_ords:
  print(df_ords['order_hour_of_day'].unique())

[ 8  7 12 15  9 14 16 11 10 19 18 17 13 20  0 21 22  5 23  4  6  1  2  3]
[ 8  7 12 15  9 14 16 11 10 19 18 17 13 20  0 21 22  5 23  4  6  1  2  3]
[ 8  7 12 15  9 14 16 11 10 19 18 17 13 20  0 21 22  5 23  4  6  1  2  3]
[ 8  7 12 15  9 14 16 11 10 19 18 17 13 20  0 21 22  5 23  4  6  1  2  3]
[ 8  7 12 15  9 14 16 11 10 19 18 17 13 20  0 21 22  5 23  4  6  1  2  3]
[ 8  7 12 15  9 14 16 11 10 19 18 17 13 20  0 21 22  5 23  4  6  1  2  3]


I may just be reading the numbers incorrectly, but the max on days_since_prior_order only showing a 3 seems to be very very low. All of those numbers seem to be low, given that we looked at the days_since_prior_order for user_id 1 and they had double digit days. 

#### Step 3

In [30]:
# Checking for mixed-types columns
for col in df_ords.columns.tolist():
  weird = (df_ords[[col]].applymap(type) != df_ords[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_ords[weird]) > 0:
    print (col)

#### Step 5

In [31]:
# Checking for missing values within df_ords
df_ords.isnull().sum()

order_id                  0
user_id                   0
order_number              0
order_day_of_week         0
order_hour_of_day         0
days_since_prior_order    0
dtype: int64

days_since_prior_order has NaN for a number of values. My theory is that this is what generates on the first order for each customer. 

#### Step 6

In [32]:
# Testing my theory about missing values in days_since_prior_order
df_ords['user_id'].nunique()

206209

REVISED: Because in this case the null value works as a flag to show that this is the customer's first order, it serves a specific purpose and should not be revised out. Thus, the "missing values" in this case are not really "missing" values and do not need to be further addressed. 

#### Step 7

In [33]:
# Pulling duplicates into new dataframe
df_ords_dupes = df_ords[df_ords.duplicated()]

In [34]:
# Checking new duplicates dataframe
df_ords_dupes.shape

(0, 6)

#### Step 8

Pulling the duplicates out of df_ords yielded no full duplicates

#### Step 9

In [35]:
# Exporting final cleaned data
df_ords.to_csv(os.path.join(path, '02 Data', 'Cleaned', 'orders_cleaned.csv'))

In [36]:
df_prods_clean_no_dupes.to_csv(os.path.join(path, '02 Data', 'Cleaned', 'products_cleaned.csv'))